name: 🐛 Bug Report
description: Report a bug in the Shongkot mobile app
title: "[Bug]: "
labels: ["type: bug", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us fix it.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by this bug?
      options:
        - Authentication
        - Emergency System
        - Contacts Management
        - Responder Features
        - Maps & Location
        - Notifications
        - Messaging/Chat
        - Media (Photo/Video/Audio)
        - Profile & Settings
        - UI/UX
        - Backend Integration
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - P0 - Critical (App crashes / Data loss)
        - P1 - High (Major feature broken)
        - P2 - Medium (Feature partially broken)
        - P3 - Low (Minor issue / Cosmetic)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: On which platform does this bug occur?
      options:
        - Android
        - iOS
        - Both Android & iOS
      multiple: false
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of the app are you using?
      placeholder: "e.g., 1.0.0+1"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device & OS Version
      description: What device and OS version are you using?
      placeholder: "e.g., Pixel 6, Android 13 or iPhone 14, iOS 16.5"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recording
      description: If applicable, add screenshots or screen recordings to help explain the problem
      placeholder: Drag and drop images or videos here
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If available, paste any relevant error logs
      placeholder: |
        Paste error logs here (use code blocks for formatting)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen consistently or intermittently?
        - Does it happen only with certain data or in certain conditions?
        - Any recent changes before this bug appeared?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check all that apply
      options:
        - label: I have searched for similar bugs in existing issues
          required: true
        - label: I can consistently reproduce this bug
          required: false
        - label: This bug affects production/released version
          required: false
