name: 🚀 Feature Request
description: Suggest a new feature for the Shongkot mobile app
title: "[Feature]: "
labels: ["type: feature", "status: needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the information below.

  - type: dropdown
    id: phase
    attributes:
      label: Development Phase
      description: Which development phase does this feature belong to?
      options:
        - Phase 1 - Foundation & Core Features
        - Phase 2 - Communication & Notifications
        - Phase 3 - Responder Integration
        - Phase 4 - Maps & Navigation
        - Phase 5 - Media & Evidence
        - Phase 6 - Advanced Features
        - Phase 7 - Platform & Polish
        - Phase 8 - Testing & Release
        - Future / Not Planned
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this feature affect?
      options:
        - Authentication
        - Emergency System
        - Contacts Management
        - Responder Features
        - Maps & Location
        - Notifications
        - Messaging/Chat
        - Media (Photo/Video/Audio)
        - Profile & Settings
        - UI/UX
        - Backend Integration
        - Testing
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - P0 - Critical (Blocks release)
        - P1 - High (Important for release)
        - P2 - Medium (Should have)
        - P3 - Low (Nice to have)
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) should this feature target?
      options:
        - Both Android & iOS
        - Android only
        - iOS only
      multiple: false
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: |
        What is the feature?
        Why is it needed?
        How should it work?
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe this feature as a user story
      placeholder: |
        As a [type of user]
        I want [an action]
        So that [a benefit/value]
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the requirements for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: false

  - type: textarea
    id: design-mockups
    attributes:
      label: Design Mockups or References
      description: Add any design mockups, wireframes, or reference links
      placeholder: |
        Upload images or provide links to similar features in other apps
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Implementation Notes
      description: Any technical considerations or suggestions for implementation?
      placeholder: |
        - Dependencies needed
        - API endpoints required
        - Third-party services
        - Performance considerations
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the feature request
    validations:
      required: false
